# site properties and page defaults
title: Steif Lab 
subtitle: Developing and applying computational methods for single cell technology
description: Dr. Adi Steif's research concentrates on utilizing computational methods to analyze high-throughput genomics data, primarily within cancer research, to understand disease mechanisms and evolution. By leveraging new measurement technologies, particularly at the single-cell level, and employing statistical machine learning techniques, the Steif Lab collaborates with experimentalists to extract biological insights from complex datasets, overcoming challenges such as noise and measurement bias.
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: steif@bcgsc.ca
  orcid: 0000-0001-8713-9213
  google-scholar: ETJoidYAAAAJ


### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
